:rootdir: ../../..
:github-readme: {rootdir}/README.adoc
:srcdir: {rootdir}/src/
:listing-caption: Listing
:revdate: {project-builddate}
:revnumber: {project-version}

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please git-link:self[edit it on GitHub, edit].

== Description

The main class is called `HtmlPublishHelper` and can be used in a gradle build to perform operations on HTML files.

Example setup:
Imagine you have several files (`case1/index.html`, `case2/page1.html`, `case2/sub/page1.html` in the example bellow) that are sharing resources in folders that are somewhere else (`assets/` or `imgs/`)

----
inputFolder
├── assets
│   ├── empty.js
│   ├── file.css
│   └── page.css
├── case1
│   └── index.html
├── case2
│   ├── page1.html
│   └── sub
│       └── page2.html
└── imgs
    ├── image.png
    └── img.svg
----

If you run `HtmlPublishHelper.publishHtmlFile(inputFile, inputFolder, outputFolder)` for the `case1/index.html` file.
You will get the html rewritten with the resources moved in appropriate sub-folders (`css/`, `images/` and `js/`).

----
outputFolder
├── css
│   └── file.css
├── images
│   ├── image.png
│   └── img.svg
├── index.html
└── js
    └── empty.js
----

To move all the html files of a folder, `HtmlPublishHelper.publishHtmlFolder(inputFolder, outputFolder)` can be used.

== Source Code

As for any java project, the source code of the plugin is available in the git-link:src/[src/] folder.

=== Build

This project is using gradle.

Command to build the sources locally:

----
./gradlew build
----

Command to deploy to your local maven repository:

----
./gradlew publishToMavenLocal
----

Command to build the documentation page:

----
./gradlew asciidoctor
----

The output of this command is an HTML page located at `<git repo root>/build/docs/html5/index.html`.

==== For project maintainers

`signing.gnupg.keyName` and `signing.gnupg.passphrase` are expected to be set in your local `gradle.properties` file to be able to sign.
`sonatypeUser` and `sonatypePassword` are expected to be set in order to be able to publish to a distant repository.
					
Command to build and publish the result to maven central:

----
./gradlew publishToSonatype
----

Command to upload the documentation page on GitHub pages:

----
./gradlew gitPublishPush
----

Command to perform a release:

----
./gradlew release -Prelease.useAutomaticVersion=true
----

==== Using ssh-agent

Some tasks requires to push into the distant git repository (release task or updating the `gh-pages` branch).
If they are failing with errors like this:
----
org.eclipse.jgit.api.errors.TransportException: ... Permission denied (publickey).
---- 

Then `ssh-agent` can be used.
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
----
(link:https://superuser.com/a/990447/[source] for this approach)


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

